# Generated by Django 4.2.3 on 2023-09-14 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_mail', models.EmailField(max_length=254, unique=True)),
                ('patient_age', models.IntegerField()),
                ('patient_address', models.CharField(max_length=100)),
                ('patient_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patientId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs_name', models.CharField(max_length=100)),
                ('docs_desc', models.TextField()),
                ('docs_image', models.ImageField(upload_to='docs')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='meds.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meds.patientid'),
        ),
    ]
