# Generated by Django 4.2.3 on 2023-09-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_doctorid_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdocument',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='pat_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
