# Generated by Django 4.2.3 on 2023-10-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0005_rename_doctor_experties_doctor_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_specialization',
            field=models.CharField(max_length=100),
        ),
    ]
