# Generated by Django 4.2.3 on 2023-10-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0011_remove_appointment_appointment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='meds.appointmentid'),
            preserve_default=False,
        ),
    ]
