# Generated by Django 4.2.3 on 2023-10-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0014_alter_appointmentid_appointment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
