# Generated by Django 4.2.3 on 2023-10-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0015_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meds.doctorid')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meds.patientid')),
            ],
        ),
        migrations.DeleteModel(
            name='AppointmentId',
        ),
    ]
