# Generated by Django 4.2.3 on 2023-10-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0016_appointment_delete_appointmentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_id',
            field=models.CharField(max_length=100),
        ),
    ]
