# Generated by Django 4.2.3 on 2023-10-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0019_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='doctor_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patient_id',
            field=models.CharField(max_length=100),
        ),
    ]
