# Generated by Django 4.2.3 on 2023-10-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0021_coffee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
