# Generated by Django 4.2.3 on 2023-10-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0022_delete_coffee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
